### ISSUE TITLE
Error "TypeError: Cannot read property 'registerType' of undefined (line:194)"

### ISSUE THREAD

**Issue by MatthiasRichwin** [signl4/node-red-contrib-signl4#1] opened 2020-07-16 06:39 UTC
node-red-contrib-signl4 1.3.0
Node-Red 1.1.1

![grafik](https://user-images.githubusercontent.com/68369118/87635647-b282b900-c73f-11ea-9aad-04410237c153.png)

**Comment by MatthiasRichwin** [comment] 2020-07-16 06:46
Checking signl4.js - it has only 185 lines?!?

**Comment by MatthiasRichwin** [comment] 2020-07-16 07:10
Looks like my local signal4.js was broken, replaced it with the original one from here - works. Don't know why I received a broken file.

**Comment by GeorgWolter** [comment] 2021-01-10 09:02
Having the same problem. Solution is really to replace signal4.js ...?
I ran this command but no success in fixing the error: npm install node-red-contrib-signl4
My current understanding is that the original signl4.js has 185 lines. So I think the root cause is somewhere else.
![Bildschirmfoto 2021-01-10 um 09 59 37](https://user-images.githubusercontent.com/61526104/104118614-b37d5780-532a-11eb-9fb3-f0219d1b30ff.jpeg)

**Comment by rons4** [comment] 2021-01-11 16:09
Sorry for the late reply. The issue should be fixed now with version 1.8.

**Comment by GeorgWolter** [comment] 2021-01-11 17:09
Retest PASSED. Thank you Ron👍

**Comment by rons4** [comment] 2021-01-11 17:15
@GeorgWolter, thank you for your feedback and good to hear.

**Comment by rons4** [comment] 2021-01-11 17:15
Fixed and tested successfully now.

**Closed as completed by rons4** 2021-01-11 17:15 UTC
